name: Publish Helm Chart

on:
  push:
    paths:
      - 'helm/trojanchat/**'
    branches:
      - main

jobs:
  package-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package chart
        run: |
          helm package helm/trojanchat --destination packaged-charts

      - name: Create or update Helm repo index
        run: |
          helm repo index packaged-charts --url https://Trojan3877.github.io/AlgoQuant-Backtester-Signal-Engine/helm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged-charts
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
