name: Mobile CI

on:
  push:
    paths:
      - 'TrojanChat/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'TrojanChat/**'
    branches: [ main ]

jobs:
  android:
    name: Build & Test Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK
        uses: malinskiy/action-android@v2
        with:
          api-level: 31
          build-tools: '31.0.0'
          ndk: false

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run Android build via Fastlane
        uses: maierj/fastlane-action@v2
        with:
          lane: android ci

  ios:
    name: Build & Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          brew install cocoapods
          bundle install

      - name: Run iOS build via Fastlane
        uses: maierj/fastlane-action@v2
        with:
          lane: ios ci


mkdir -p TrojanChat/.github/workflows
mv .github/workflows/mobile-ci.yml TrojanChat/.github/workflows/
git add TrojanChat/.github/workflows/mobile-ci.yml
git commit -m "Add mobile CI workflow for TrojanChat (Android & iOS via Fastlane)"
git push
