apiVersion: v1
kind: Service
metadata:
  name: trojanchat-service
  labels:
    app: trojanchat
spec:
  type: ClusterIP
  selector:
    app: trojanchat
  ports:
    - port: 80
      targetPort: 8080
      name: http
